### ISSUE TITLE
Official Solutions Throws Errors

### ISSUE THREAD

**Issue by taiga-ghs** [NZOI/website#31]
The solutions in the NZIC 2019 Round 2 Official Solutions PDF for “An Average Problem” doesn’t pass through every test case on training site.

**Comment by Holmes98** [comment]
I have checked and can confirm that model solution is correct.

The published solution did introduce a minor typo but this should not affect your ability to understand it. The full solution is intentionally incomplete to encourage students to take the time to read through and understand the subtasks rather than just copy-paste our solution onto the training site.
